apiVersion: apps/v1
kind: Deployment
metadata:
  name: coordinator
  namespace: devfest
  labels:
    app: coordinator
    component: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coordinator
  template:
    metadata:
      labels:
        app: coordinator
        component: frontend
    spec:
      containers:
      - name: coordinator
        image: localhost:5000/devfest-coordinator:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8501
          name: http
        env:
        - name: OLLAMA_HOST
          value: "http://host.k3d.internal:11434"
        - name: OLLAMA_MODEL
          value: "gemma3n:latest"
        - name: PYTHONPATH
          value: "/app/src"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /_stcore/health
            port: 8501
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /_stcore/health
            port: 8501
          initialDelaySeconds: 10
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: coordinator
  namespace: devfest
  labels:
    app: coordinator
spec:
  type: NodePort
  ports:
  - port: 8501
    targetPort: 8501
    nodePort: 30850
    protocol: TCP
    name: http
  selector:
    app: coordinator
